basePath: /v1/api
definitions:
  main.ErrorResponse:
    properties:
      error:
        example: error message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: stream service
  title: stream
  version: "1.0"
paths:
  /:
    get:
      parameters:
      - description: cmd work path
        in: query
        name: path
        required: true
        type: string
      - description: cmd execute
        in: query
        name: cmd
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: string
      summary: Request cmd path
      tags:
      - streams
  /close:
    get:
      parameters:
      - description: push rtmp url
        in: header
        name: push
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: string
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Close stream push
      tags:
      - streams
  /log:
    get:
      responses:
        "200":
          description: successful operation
          schema:
            type: string
      summary: Print logger file
      tags:
      - streams
  /push:
    get:
      parameters:
      - description: force to push
        in: header
        name: force
        type: string
      - description: push rtmp url
        in: header
        name: push
        required: true
        type: string
      responses:
        "202":
          description: successful operation
          schema:
            type: string
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: server error request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Start push stream
      tags:
      - streams
  /run:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: successful operation
          schema:
            additionalProperties: true
            type: object
      summary: Start run time
      tags:
      - streams
  /upstart:
    get:
      parameters:
      - description: https file download url
        in: header
        name: url
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: string
        "400":
          description: invalid downalod url
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: file operation failure
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Upstart Service
      tags:
      - streams
swagger: "2.0"
