basePath: /
definitions:
  main.ErrorResponse:
    properties:
      error:
        example: error message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: serveless service
  title: serveless
  version: v
paths:
  /:
    get:
      responses:
        "200":
          description: successful operation
          schema:
            type: string
        "400":
          description: error bad request
          schema:
            type: string
        "500":
          description: server error request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Start push stream
      tags:
      - serverless
  /api/{id}:
    delete:
      parameters:
      - description: execute
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: string
        "202":
          description: successful operation
          schema:
            type: string
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: server error request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Start push stream
      tags:
      - serverless
    get:
      parameters:
      - description: execute
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: string
        "202":
          description: successful operation
          schema:
            type: string
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: server error request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Start push stream
      tags:
      - serverless
    options:
      parameters:
      - description: execute
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: string
        "202":
          description: successful operation
          schema:
            type: string
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: server error request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Start push stream
      tags:
      - serverless
    post:
      parameters:
      - description: execute
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: string
        "202":
          description: successful operation
          schema:
            type: string
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: server error request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Start push stream
      tags:
      - serverless
    put:
      parameters:
      - description: execute
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: string
        "202":
          description: successful operation
          schema:
            type: string
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
        "500":
          description: server error request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Start push stream
      tags:
      - serverless
swagger: "2.0"
