name: android
on:
  workflow_dispatch:
    inputs:
      

jobs:
  android:
    runs-on: macos-lastest
    strategy:
      matrix:
        api-level: [23]

    steps:
    - name: Setup Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Run
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: arm64-v8a
        script: ./gradlew connectedCheck

