name: breaktap
on:
  push:
    branches: master

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1.3
        with:
          version: latest
          platform: x64

      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: mingw64
          install: >-
            autotools
            make
          location: D:\

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Build Code
        run: |
          echo "##[add-path]D:\autotools;"
          git clone https://github.com/DaemonEngine/breakpad.git
          cd breakpad
          git clone https://github.com/google/googletest.git src/testing
          git clone https://github.com/google/protobuf.git src/third_party/protobuf/protobuf
          git clone https://chromium.googlesource.com/external/gyp src/tools/gyp
          autoreconf -fvi
          .\configure && make
