name: breaktap
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: 'v1.7.3'

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Set up Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build Code
        run: |
          git clone https://github.com/DaemonEngine/breakpad.git
          python3 .\fetch-externals
          autoreconf -fvi
          .\configure && make
