name: cctv2
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'download url'
        required: true
        default: ''
      fileid:
        description: 'fileid name'
        required: true
        default: ''


jobs:
  cctv2:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.14' ]

    steps:
    - name: Use Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Download
      run: bash script/cctv2.sh ${{github.event.inputs.url}}

    - name: Upload
      if: ${{ success() && env.VEDIO}}
      run: |
        make -C golang upload && \
        ./golang/upload -upload -dir vedio -file ${{env.VEDIO}} &&\
        ./golang/upload -delete -fileid  ${{github.event.inputs.fileid}}
