name: email
on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  email:
    runs-on: ubuntu-latest
    env:
      go: '1.17'

    steps:
    - name: Use Go ${{ env.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.go }}

    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Delete emails
      timeout-minutes: 30
      run: |
        make -C golang email && \
        golang/email -u ${{secrets.EMAIL_USERNAME}} -p ${{secrets.EMAIL_PASSWORD}}
      shell: bash
