name: email
on:
  schedule:
  - cron: '*/30 * * * *'

jobs:
  email:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Delete emails
      timeout-minutes: 10
      run: |
        make -C golang email && \
        golang/email -u ${{secrets.EMAIL_USERNAME}} -p ${{secrets.EMAIL_PASSWORD}}
