name: email
on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  email:
    runs-on: ubuntu-latest
    env:
      go: '1.17'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          repository: tiechui1994/free
          token: ${{secrets.GIT_TOKEN}}
          path: ./action
      - uses: ./action/action/email
        with:
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}