name: email
on:
  push:
    branches: master
  schedule:
  - cron: '*/10 * * * *'

jobs:
  email:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout code
      timeout-minutes: 1
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: drop emails
      timeout-minutes: 5
      run: |
        make -C golang mail && \
        golang/mail -u ${{secrets.EMAIL_USERNAME}} -p ${{secrets.EMAIL_PASSWORD}}
