name: free
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:
    inputs:
      tody:
        description: 'date'
        required: false
        default: ''

jobs:
  free:
    runs-on: ubuntu-latest
    env:
      go: '1.17'

    steps:
      - name: Use Go ${{ env.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go }}

      - name: Checkout
        timeout-minutes: 1
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Pull
        timeout-minutes: 120
        run: |
          echo "inputs date: ${{github.event.inputs.tody}}"
          make -C golang free && \
          golang/free -cache https://api.quinn.eu.org/api/mongo \
          -config ${{secrets.CONFIG}} \
          -date "${{github.event.inputs.tody}}"
        shell: bash
