name: free
on:
  schedule:
    - cron: '0 */8 * * *'
  push:
    branches: master

jobs:
  free:
    runs-on: ubuntu-latest
    env:
      go: '1.17'

    steps:
      - name: Use Go ${{ env.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go }}

      - name: Checkout
        timeout-minutes: 1
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Pull
        timeout-minutes: 30
        run: |
          make -C golang free && \
          golang/free -cache https://api.quinn.eu.org/api/mongo -config ${{secrets.CONFIG}}
        shell: bash
