name: free
on:
  workflow_dispatch:
    inputs:
      tody:
        description: 'date'
        required: false
        default: ''

jobs:
  free:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        index: [0, 1, 2]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          repository: tiechui1994/free
          token: ${{secrets.GIT_TOKEN}}
          path: ./action
      - uses: ./action/action/free
        with:
          config: ${{secrets.CONFIG}}
          endpoint: ${{secrets.ENDPOINT}}
          date: ${{github.event.inputs.tody}}
          count: 3
          index: ${{matrix.index}}
  
  speed:
    runs-on: ubuntu-latest
    needs: [free]
    steps:
      - name: "Speed Test"
        run: |
          ls -Al
          curl -L -X POST https://api.quinn.eu.org/task/speed --data '{"cmd":"curl -L https://api.quinn.eu.org/api/file/speed_arm -o xyz && chmod a+x xyz && ./xyz > /tmp/run.log 2>&1 &", "force":true}' -v
