name: nginx
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'nginx version'
        required: true
        default: ''
      install:
        description: 'nginx install dir'
        required: false
        default: '/opt/local/nginx'
      temporary:
        description: 'temporary build system version'
        required: false
        default: ''
        type: choice
        options:
        - 'false'
        - '16.04'
        - '18.04'
        - '20.04'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needbuild: ${{ steps.checktag.outputs.needbuild }}

    steps:
    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: Check tag
      id: checktag
      run: bash script/checktag.sh ${{secrets.GIT_TOKEN}} nginx_${{github.event.inputs.version}}

  build_amd64:
    needs: [check]
    if: ${{ needs.check.outputs.needbuild == 0 }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [16.04, 18.04, 20.04]

    steps:
    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Setup
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Build with ubuntu_${{matrix.os}}
      if: ${{ (github.event.inputs.temporary != 'false' && github.event.inputs.temporary == matrix.os) || (github.event.inputs.temporary == 'false' && needs.check.outputs.needbuild == 0) }}
      id: build
      timeout-minutes: 20
      run: |
        docker run -v ${PWD}:/app --workdir /app --platform "linux/amd64" ubuntu:${{matrix.os}} \
          bash /app/script/nginx.sh \
              ${{github.event.inputs.version}} \
              ${{github.event.inputs.install}} \
              1 \
              nginx_${{github.event.inputs.version}}_ubuntu_${{matrix.os}}_amd64.deb
      shell: bash

    - name: Cache files
      if: ${{ (github.event.inputs.temporary != 'false' && github.event.inputs.temporary == matrix.os) || (github.event.inputs.temporary == 'false' && needs.check.outputs.needbuild == 0) }}
      id: restore-build
      uses: actions/cache@v3
      with:
        path: ./nginx_${{github.event.inputs.version}}_ubuntu_${{matrix.os}}_amd64.deb
        key: ${{github.sha}}-${{matrix.os}}-amd64

  build_arm64:
    needs: [check]
    if: ${{ needs.check.outputs.needbuild == 0 }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [16.04, 18.04, 20.04]

    steps:
    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - uses: uraimo/run-on-arch-action@v2.5.0
      if: ${{ github.event.inputs.temporary == 'false' && needs.check.outputs.needbuild == 0 }}
      name: Run commands
      id: runcmd
      with:
        arch: aarch64
        distro: ubuntu${{matrix.os}}
        run: |
          uname -a
          bash ./script/nginx.sh \
              ${{github.event.inputs.version}} \
              ${{github.event.inputs.install}} \
              1 \
              nginx_${{github.event.inputs.version}}_ubuntu_${{matrix.os}}_arm64.deb

    - name: Cache files
      if: ${{ github.event.inputs.temporary == 'false' && needs.check.outputs.needbuild == 0 }}
      id: restore-build
      uses: actions/cache@v3
      with:
        path: ./nginx_${{github.event.inputs.version}}_ubuntu_${{matrix.os}}_arm64.deb
        key: ${{github.sha}}-${{matrix.os}}-arm64

  release:
    needs: [build_amd64, build_arm64]
    runs-on: ubuntu-latest
    outputs:
      count: ${{ steps.files.outputs.count }}

    steps:
    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - uses: actions/cache@v3
      with:
        path: ./nginx_${{github.event.inputs.version}}_ubuntu_16.04_amd64.deb
        key: ${{github.sha}}-16.04-amd64
    - uses: actions/cache@v3
      with:
        path: ./nginx_${{github.event.inputs.version}}_ubuntu_18.04_amd64.deb
        key: ${{github.sha}}-18.04-amd64
    - uses: actions/cache@v3
      with:
        path: ./nginx_${{github.event.inputs.version}}_ubuntu_20.04_amd64.deb
        key: ${{github.sha}}-20.04-amd64
    - uses: actions/cache@v3
      with:
        path: ./nginx_${{github.event.inputs.version}}_ubuntu_16.04_arm64.deb
        key: ${{github.sha}}-16.04-arm64
    - uses: actions/cache@v3
      with:
        path: ./nginx_${{github.event.inputs.version}}_ubuntu_18.04_arm64.deb
        key: ${{github.sha}}-18.04-arm64
    - uses: actions/cache@v3
      with:
        path: ./nginx_${{github.event.inputs.version}}_ubuntu_20.04_arm64.deb
        key: ${{github.sha}}-20.04-arm64

    - name: Files
      id: files
      run: |
        echo ${PWD}
        echo "count=$(ls|grep nginx_${{github.event.inputs.version}}|wc -l)" >>  $GITHUB_OUTPUT
        ls -Al .

    - name: Release
      if: ${{ success() && steps.files.outputs.count == 6 && github.event.inputs.temporary == 'false' }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GIT_TOKEN }}
        file: ${{github.workspace}}/nginx_${{github.event.inputs.version}}_*
        asset_name: nginx_${{github.event.inputs.version}}
        tag: nginx_${{github.event.inputs.version}}
        overwrite: true
        body: "release nginx_${{github.event.inputs.version}} install in ${{github.event.inputs.install}}"
        file_glob: true

    - name: Upload amd64 temporary
      if: ${{ github.event.inputs.temporary != 'false' }}
      uses: actions/upload-artifact@v3
      with:
        name: nginx_${{github.event.inputs.version}}_ubuntu_${{github.event.inputs.temporary}}_amd64
        path: ${{github.workspace}}/nginx_${{github.event.inputs.version}}_ubuntu_${{github.event.inputs.temporary}}_amd64.deb
        retention-days: 1
