name: pgsql
on:
  push:
    branches: master

jobs:
  pgsql:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Build
      id: build
      timeout-minutes: 60
      run: |
        bash script/pgsql.sh ${{ secrets.GIT_TOKEN }} 12.0
      shell: bash

#    - name: Release
#      timeout-minutes: 1
#      if: ${{env.DEB}}
#      uses: svenstaro/upload-release-action@v2
#      with:
#        repo_token: ${{ secrets.GIT_TOKEN }}
#        file: ${{github.workspace}}/pgsql_*
#        asset_name: ${{env.DEB}}
#        tag: ${{env.TAG}}
#        overwrite: true
#        body: "release ${{env.TAG}}"
#        file_glob: true