name: redis
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'redis version'
        required: true
        default: ''
      install:
        description: 'redis install dir'
        required: false
        default: '/opt/local/redis'

jobs:
  redis:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        timeout-minutes: 1
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        id: build
        timeout-minutes: 10
        run: |
          bash script/redis.sh ${{ secrets.GIT_TOKEN }} ${{github.event.inputs.version}} ${{github.event.inputs.install}}
        shell: bash

      - name: Release
        timeout-minutes: 1
        if: ${{ success() && env.DEB }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GIT_TOKEN }}
          file: ${{github.workspace}}/redis_*
          asset_name: ${{env.DEB}}
          tag: ${{env.TAG}}
          overwrite: true
          body: "release ${{env.TAG}}, install in ${{github.event.inputs.install}}"
          file_glob: true