name: tzdata
on:
  push:
    branches: master

jobs:
  tzdata:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: TzData
      run: bash script/tzdata.sh
