name: upload
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'download url'
        required: true
        default: ''
      name:
        description: 'file name'
        required: true
        default: ''
#  push:
#    branches: master

jobs:
  upload:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.14' ]

    steps:
      - name: Use Go ${{ matrix.go }}
        uses: actions/setup-node@v1
        with:
          go: ${{ matrix.go }}

      - name: Checkout
        timeout-minutes: 1
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Download ${{github.event.inputs.name}}
        if: ${{ github.event.inputs.url && github.event.inputs.name }}
        run: bash script/download.sh ${{github.event.inputs.name}} ${{github.event.inputs.url}}

      - name: Upload
        if: ${{ success() }}
        run: |
          go run golang/*.go -t ${{secrets.PAN_TOKEN}} -f ${{github.event.inputs.url}}
