name: upload
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'download url'
        required: true
        default: ''
      name:
        description: 'file name'
        required: true
        default: ''

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      go: '1.17'

    steps:
    - name: Use Go ${{ env.go }}
      uses: actions/setup-go@v3
      with:
        check-latest: true
        go-version: ${{ env.go }}

    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Download ${{github.event.inputs.name}}
      if: ${{ github.event.inputs.url && github.event.inputs.name }}
      run: bash script/download.sh $NAME ${{github.event.inputs.url}}
      env:
        NAME: ${{github.event.inputs.name}}

    - name: Upload
      if: ${{ success() }}
      run: |
        make -C golang upload
        golang/upload -upload -file $NAME
      shell: bash
      env:
        NAME: ${{github.event.inputs.name}}
        ALIDRIVE_TOKEN: ${{secrets.ALIDRIVE_TOKEN}}
