name: upload
on:
  push:
    branches: master

jobs:
  upload:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.14' ]

    steps:
      - name: Use Go ${{ matrix.go }}
        uses: actions/setup-node@v1
        with:
          go: ${{ matrix.go }}

      - name: Checkout
        timeout-minutes: 1
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Download
        run: bash script/download.sh $name $url
        env:
          url: https://github.com/jgraph/drawio-desktop/releases/download/v14.6.13/drawio-amd64-14.6.13.deb
          name: drawio-amd64-14.6.13.deb

      - name: Upload
        timeout-minutes: 30
        run: |
          go run golang/*.go -t ${{secrets.PAN_TOKEN}} -f $name
        env:
          name: drawio-amd64-14.6.13.deb
