name: video
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'ts download url'
        required: true
        default: ''
      parallel:
        description: 'parallel count'
        required: false
        default: 10
      name:
        description: 'name'
        required: false
        default: 'video.mpg'
      target:
        description: 'name'
        required: false
        default: 'videos'

jobs:
  video:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17' ]

    steps:
    - name: Use Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Downalod and Upload
      run: |
        name=${{github.workspace}}/${{github.event.inputs.name}}
        make -C golang vedio
        golang/vedio -name ${name} -url ${{github.event.inputs.url}} -batch ${{github.event.inputs.parallel}}
        arr=($(du -mh $name))
        echo "${arr[1]} size: ${arr[0]}B"
        make -C golang upload
        export ALIDRIVE_TOKEN=${{secrets.ALIDRIVE_TOKEN}}
        golang/upload -upload -file ${name} -dir ${{github.event.inputs.target}}

