name: video
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'ts download url'
        required: true
        default: ''
      parallel:
        description: 'parallel count'
        required: false
        default: 10
      name:
        description: 'name'
        required: false
        default: 'video.mpg'
      target:
        description: 'name'
        required: false
        default: 'videos'
      delay:
        description: 'delay second'
        required: false
        default: 0

jobs:
  video:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17' ]

    steps:
    - name: Use Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Downalod and Upload
      run: |
        make -C golang vedio
        sleep ${{github.event.inputs.delay}}
        golang/vedio -name $NAME -url ${{github.event.inputs.url}} -batch ${{github.event.inputs.parallel}}
        arr=($(du -mh $NAME))
        echo "${arr[1]} size: ${arr[0]}B"
        make -C golang upload
        golang/upload -upload -file $NAME -dir ${{github.event.inputs.target}}
      env:
        NAME: ${{github.workspace}}/${{github.event.inputs.name}}
        ALIDRIVE_TOKEN: ${{secrets.ALIDRIVE_TOKEN}}

