name: youtube
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'video url'
        required: true
        default: ''
      name:
        description: 'video name'
        required: true
        default: ''
      quality:
        description: 'video quality'
        required: false
        default: 720
        type: choice
        options:
          - 360
          - 480
          - 720
          - 1080
          - 1440
          - 2160
          - 4320
      fps:
        description: 'video fps'
        required: false
        default: 30
        type: choice
        options:
          - 15
          - 25
          - 30
          - 60
      convert:
        description: 'convert video'
        required: false
        default: false
        type: choice
        options:
          - true
          - false

jobs:
  vedio:
    runs-on: ubuntu-latest
    env:
      go: '1.17'

    steps:
    - name: Use Go ${{ env.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.go }}

    - name: Checkout
      timeout-minutes: 1
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Downalod
      run: |
        wget --quiet  https://github.com/tiechui1994/actions/releases/download/ffmpeg_5.1/ffmpeg.tar.xz -O ffmpeg.tar.xz
        tar xf ffmpeg.tar.xz && chmod a+x ffmpeg/ffmpeg && chmod a+x ffmpeg/ffprobe
        make -C golang youtube
        golang/youtube -name $NAME -url $URL -quality $QUALITY -fps $FPS -ffmpeg ffmpeg/ffmpeg -ffprobe ffmpeg/ffprobe
      env:
        NAME: ${{github.workspace}}/${{github.event.inputs.name}}
        URL: ${{github.event.inputs.url}}
        QUALITY: ${{github.event.inputs.quality}}
        FPS: ${{github.event.inputs.fps}}

    - name: Convert
      if: ${{ success() && github.event.inputs.convert != 'false' }}
      run: |
        cd ${{github.workspace}}
        name=$(ls|grep $NAME)
        echo "ext: ${name##*.}"
        if [[ "${name##*.}" != "mp4" ]]; then
          name=$(ls|grep $NAME)
          ffmpeg/ffmpeg -i "$name" -crf 20 -c:v libx264 "${NAME}.mp4"
          if [[ $? -eq 0 ]]; then
            rm -rf ${name}
          fi
        fi
        ls -lh
      env:
        NAME: ${{github.event.inputs.name}}
        
    - name: Upload
      if: ${{ success() }}
      run: |
        name=$(ls|grep $NAME)
        make -C golang upload
        golang/upload -upload -file "${{github.workspace}}/${name}"
      env:
        ALIDRIVE_TOKEN: ${{secrets.ALIDRIVE_TOKEN}}
        NAME: ${{github.event.inputs.name}}

